### ISSUE TITLE
Sending wav - speech recognitoin

### ISSUE THREAD

**Issue by ignaszewski** [wit-ai/node-wit#105]
Is there feature where I can send speech file by node app?

**Comment by stopachka** [comment]
cc @blandinw for thoughts

hey @ignaszewski, this was included in the old sdk (https://github.com/wit-ai/DEPRECATED-node-wit/blob/master/lib/wit.js#L70), but is no longer included in this one.

It may be good to add it once more, will ping the team for thoughts

**Comment by blandinw** [comment]
Sure, we merged that into pywit recently: https://github.com/wit-ai/pywit/pull/67

**Comment by Sultan91** [comment]
Hi, as far as I know http post request has a feature for sending .wav file: 
![screenshot](https://cloud.githubusercontent.com/assets/16382530/21481766/85471d68-cb7c-11e6-9d07-7dddc2a9a452.jpg)

Can you please guide me of how to make the same with  jQuery Ajax POST. I've tried this way:
 
![screenshot001](https://cloud.githubusercontent.com/assets/16382530/21481825/3f35c0a8-cb7d-11e6-8dac-12fe5319acf0.jpg)
data geenrated like that: `var data = new FormData();
	data.append('file',$('input[type=file]')[0].files[0]);`
It gives illegal invocation error.

**Comment by scott-harrison** [comment]
Will this feature be added back into node-wit?

**Comment by Sultan91** [comment]
I beleive it has been depricated already, if  I am not mistaking(

**Comment by scott-harrison** [comment]
was there a reason for its deprecation? Cause I really would like to use it.

**Comment by blandinw** [comment]
We've decided not to add speech recognition to the SDK because we want the SDK to run on different platforms:
- nodejs running on Linux on a Raspberry Pi
- nodejs running on macOS on a Macbook
- browser
- react-native

We had the same issue in the Python SDK: https://github.com/wit-ai/pywit/blob/master/CHANGES.md#v20

We haven't found a good abstraction to read from the microphone, or even from a bytes stream, on all these platforms yet. We'd welcome a well-thought-out pull request, but I'm not sure it's feasible today.
