### ISSUE TITLE
Messenger example doesn't work on facebook page

### ISSUE THREAD

**Issue by geoqpcr** [wit-ai/node-wit#180]
Everything works fine when I send a test message to my app from facebook developer console, but when I try to send it from messenger I don't get any HTTP request to my app.

PD:
- I am using ngrok in order to get a valid URL.
- I am subscribed just to _conversations_.
- My facebook page is live.
- I am running the examples/messenger.js code. 

Any help is welcome. @zpao @gleuch @cdelahousse @TuniLame @blandinw 

<img width="441" alt="screen shot 2018-09-26 at 1 48 15 pm" src="https://user-images.githubusercontent.com/43180321/46102114-32b6e380-c193-11e8-8d6c-6b8ee7056e69.png">
<img width="957" alt="screen shot 2018-09-26 at 1 49 19 pm" src="https://user-images.githubusercontent.com/43180321/46102115-32b6e380-c193-11e8-99e5-49f9f578d180.png">

**Comment by blandinw** [comment]
Looking into it

**Comment by blandinw** [comment]
@geo-dev-cr this may be a bug with the Messenger API, see this bug https://developers.facebook.com/bugs/824028317765435

You can try using something other than ngrok and see if that works. I would also recommend searching for "ngrok" or asking for help in this group: https://www.facebook.com/groups/messengerplatform/

Closing now since this does not seem related to Wit.

**Comment by geoqpcr** [comment]
Thanks @blandinw.
