### ISSUE TITLE
Actions from another stories are being executed

### ISSUE THREAD

**Issue by Bhilhanan** [wit-ai/node-wit#25]
I created two stories.

Story 1: 
<img width="981" alt="screen shot 2016-04-27 at 2 39 13 am" src="https://cloud.githubusercontent.com/assets/6808950/14834253/0a88d37a-0c21-11e6-894c-bc37a915f9b7.png">

Story 2:
<img width="980" alt="screen shot 2016-04-27 at 2 39 26 am" src="https://cloud.githubusercontent.com/assets/6808950/14834258/137f9e6e-0c21-11e6-8729-49ee10bc7738.png">

Actions:

```
const actions = {
  say(sessionId, context, message, cb) {
    console.log(message);
    cb();
  },
  merge(sessionId, context, entities, message, cb) {
    const wsName = firstEntityValue(entities, 'workspace');
    if (wsName) {
      context.ws_name = wsName;
    }
    cb(context);
  },
  error(sessionId, context, error) {
    console.log(error.message);
  },
  ['fetch-ws-status'](sessionId, context, cb) {
    if(context.ws_name=='ws1'){
      context.colour = 'green';
    }else{
      context.colour = 'red';
    }
    cb(context);
  },
  ['start-ws'](sessionId,context,cb){
    console.log('invoke the url to start ws'+context.ws_name);
    cb(context);
 }
};
```

When I start the client and type "how is ws4?", I see that the action from the other story is also getting executed. Then it seems like it is invoking the two actions repeatedly.

<img width="301" alt="screen shot 2016-04-27 at 2 30 25 am" src="https://cloud.githubusercontent.com/assets/6808950/14834072/186a924a-0c20-11e6-9380-899adee069a1.png">

Am I doing something wrong ?

**Comment by patapizza** [comment]
Hi,

Sorry for the late reply. This is an issue unrelated to `node-wit`. I'll answer here, but it should really go to https://github.com/wit-ai/wit.

I see a few issues:
1) You did a spelling mistake: "w4" instead of "ws4". Hence Wit didn't find the workspace entity. As a result, your `merge` action didn't add `ws_name` to the context, and the template "Let me check `{ws_name}`" is missing the requirement.
2) According to your story, `fetch-ws-status` is expected to add `status` to the context. However, in your implementation, you're adding `colour` instead.

Hope this helps
